Select * from customer_behavior

-- Q1. What is the total revenue generated by male vs. female customers?
Select gender,Sum(purchase_amount) as revenue
from customer_behavior group by gender

-- Q2. Which customers used a discount but still spent more than the average purchase amount?
Select customer_id , purchase_amount 
from customer_behavior
where discount_applied = 'Yes' and purchase_amount >= (select AVG(purchase_amount) from customer_behavior) 

-- Q3. Which are the top 5 products with the highest average review rating?
Select Top 5 
item_purchased, Round(AVG(review_rating), 2) as "Average Product Rating"
from customer_behavior
Group by item_purchased
Order by AVG(review_rating) desc

-- Q4. Compare the average Purchase Amounts between Standard and Express Shipping.
SELECT 
    shipping_type, 
    CAST(
        ROUND(
            CAST(AVG(purchase_amount) AS DECIMAL(18,3)), 
        2)
    AS DECIMAL(18,3)) AS [Average Purchase Amount]
FROM customer_behavior
WHERE shipping_type IN ('Standard','Express')
GROUP BY shipping_type;

-- Q5. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.


SELECT DATA_TYPE, NUMERIC_PRECISION, NUMERIC_SCALE
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'customer_behavior'
  AND COLUMN_NAME = 'purchase_amount';

SELECT 
    subscription_status,
    COUNT(customer_id) AS [Total Customers],
    CAST(
    ROUND(
        AVG(CAST(purchase_amount AS DECIMAL(18,2))),2) 
        AS DECIMAL(10,2)) AS Average_Spend,

    SUM(purchase_amount) AS [Total_Revenue]
FROM customer_behavior
GROUP BY subscription_status
ORDER BY Total_Revenue desc;


-- Q6. Which 5 products have the highest percentage of purchases with discounts applied?
Select Top 5 item_purchased, 
Cast(Round(sum(case when discount_applied = 'Yes' then 1 else 0 end) * 100.0
    / count(*), 2 ) AS decimal(10,2)) as discount_rate
from customer_behavior 
group by item_purchased 
order by discount_rate desc ;

-- Q7. Segment customers into New, Returning, and Loyal based on their total number of previous purchases, and show the count of each segment.
with customer_type as(
Select customer_id , previous_purchases,
    Case
        when previous_purchases = 1 then 'New'
        when previous_purchases between 2 and 10 then 'Returning'
        else 'Loyal'
        end as customer_segment
from customer_behavior)

Select customer_segment, count(*) as 'Number of Customers'
from customer_type
group by customer_segment
order by [Number of Customers] desc

-- Q8. What are the top 3 most purchased products within each category?
with item_counts as (
    select category,
    item_purchased,
    count(customer_id) as total_orders,
    row_number() over(partition by category order by count(customer_id) desc) as item_rank
    from customer_behavior
    group by category, item_purchased
)
select item_rank, category, item_purchased, total_orders
from item_counts
where item_rank <= 3;

-- Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?

select subscription_status,
count(customer_id) as repeat_buyears
from customer_behavior
where previous_purchases > 5
group by subscription_status

-- Q10. What is the revenue contribution of each age group?

select age_group,
sum(purchase_amount) as total_revenue
from customer_behavior
group by age_group
order by total_revenue desc      
